
service: my-trips-infra

frameworkVersion: '2'

plugins:
  - serverless-deployment-bucket

custom:
  region: us-west-2
  stage: dev
  sls-deployment-bucket: my-trips-infra-sls-deployment

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region, opt:region}
  stage: ${self:custom.stage, opt:stage}
  deploymentBucket: 
    name: ${self:custom.sls-deployment-bucket}-${self:provider.stage}
# Lambda function's IAM Role 
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "dynamodb:*"
    #  Resource: "arn:aws:dynamodb:*:*:table/*"
     Resource:
      Fn::GetAtt:
       - MyTripsTable
       - Arn
   - Effect: "Allow"
     Action:
       - "logs:CreateLogStream"
       - "logs:PutLogEvents"
     Resource: "arn:aws:logs:*:*:*"
   

# service wide environment variables
  environment:
    STAGE: ${self:provider.stage}

# CloudFormation resource templates
resources:
 Resources:
   MyTripsTable:
     Type: AWS::DynamoDB::Table
     DeletionPolicy: Retain
     Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: type
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 2
      TableName: ${self:service}-my-trips-${self:custom.stage}
 Outputs:
    MyTripsTableOutput:
      Description: "Description for the output"
      Value: 
        Ref: MyTripsTable
      Export:
        Name: ${self:service}-MyTripsTable-${self:custom.stage}
